# Generated by Django 4.2.7 on 2023-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_modified',
            field=models.CharField(default=1700417263, max_length=10),
        ),
    ]
