# Generated by Django 4.2.7 on 2023-11-19 19:45

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_modified',
            field=models.CharField(default=todo.models.getTimeStamp, max_length=10),
        ),
    ]
